import { describe, it, expect } from 'vitest'
import { PBNDocument } from '../../src/pbn/pbnDocument.js'
import { PBNGame } from '../../src/pbn/pbnGame.js'

describe('PBNDocument', () => {
  it('defaults to an empty document', () => {
    const doc = new PBNDocument()
    expect(doc.games).toEqual([])
    expect(doc.escapedText).toEqual([])
  })

  it('can be constructed with initial games and escaped text', () => {
    const game = new PBNGame()
    const doc = new PBNDocument([game], ['Generated by Example Software'])
    expect(doc.games).toEqual([game])
    expect(doc.escapedText).toEqual(['Generated by Example Software'])
  })

  it('games and escapedText are mutable', () => {
    const doc = new PBNDocument()
    doc.games.push(new PBNGame())
    doc.escapedText.push('a header line')
    expect(doc.games).toHaveLength(1)
    expect(doc.escapedText).toEqual(['a header line'])
  })
})
