import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { PBNDocument } from '../../src/pbn/pbnDocument.js'
import { PBNGame } from '../../src/pbn/pbnGame.js'

const readTestData = (name: string): string =>
  readFileSync(new URL(`../../test-data/${name}`, import.meta.url), 'utf8')

describe('PBNDocument', () => {
  it('defaults to an empty document', () => {
    const doc = new PBNDocument()
    expect(doc.games).toEqual([])
    expect(doc.escapedText).toEqual([])
  })

  it('can be constructed with initial games and escaped text', () => {
    const game = new PBNGame()
    const doc = new PBNDocument([game], ['Generated by Example Software'])
    expect(doc.games).toEqual([game])
    expect(doc.escapedText).toEqual(['Generated by Example Software'])
  })

  it('games and escapedText are mutable', () => {
    const doc = new PBNDocument()
    doc.games.push(new PBNGame())
    doc.escapedText.push('a header line')
    expect(doc.games).toHaveLength(1)
    expect(doc.escapedText).toEqual(['a header line'])
  })

  describe('fromPBN', () => {
    it('an empty string has no games and no escaped text', () => {
      const doc = PBNDocument.fromPBN('')
      expect(doc.games).toEqual([])
      expect(doc.escapedText).toEqual([])
    })

    it('parses a single game into one section per tag', () => {
      const doc = PBNDocument.fromPBN('[Board "1"]\n[Dealer "N"]\n')
      expect(doc.games).toHaveLength(1)
      expect(doc.games[0]!.sections).toHaveLength(2)
      expect(doc.games[0]!.getTagValue('Board')).toBe('1')
      expect(doc.games[0]!.getBoard()).toBe(1)
      expect(doc.games[0]!.getTagValue('Dealer')).toBe('N')
      expect(doc.games[0]!.getDealer()).toBe('N')
    })

    it('a blank line separates games', () => {
      const doc = PBNDocument.fromPBN('[Board "1"]\n\n[Board "2"]\n')
      expect(doc.games).toHaveLength(2)
      expect(doc.games[0]!.getTagValue('Board')).toBe('1')
      expect(doc.games[0]!.getBoard()).toBe(1)
      expect(doc.games[1]!.getTagValue('Board')).toBe('2')
      expect(doc.games[1]!.getBoard()).toBe(2)
    })

    it('multiple consecutive blank lines still only separate two games (no empty ones between)', () => {
      const doc = PBNDocument.fromPBN('[Board "1"]\n\n\n\n[Board "2"]\n')
      expect(doc.games).toHaveLength(2)
    })

    it('leading blank lines before the first game are ignored', () => {
      const doc = PBNDocument.fromPBN('\n\n[Board "1"]\n')
      expect(doc.games).toHaveLength(1)
      expect(doc.games[0]!.getBoard()).toBe(1)
    })

    it('"%" lines before any game go to escapedText, keeping the "%" and exact whitespace', () => {
      const doc = PBNDocument.fromPBN('% PBN 2.1\n%Creator:Test\n[Board "1"]\n')
      expect(doc.escapedText).toEqual(['% PBN 2.1', '%Creator:Test'])
      expect(doc.games).toHaveLength(1)
    })

    it('a "%" line inside a section joins that section instead of escapedText', () => {
      const doc = PBNDocument.fromPBN('[Board "1"]\n%mid-section escape\n[Dealer "N"]\n')
      expect(doc.escapedText).toEqual([])
      expect(doc.games[0]!.sections[0]!.lines).toEqual(['[Board "1"]', '%mid-section escape'])
    })

    it('content before a game\'s first tag becomes its "global" untagged section', () => {
      const doc = PBNDocument.fromPBN('; a comment about the game\n[Board "1"]\n')
      expect(doc.games).toHaveLength(1)
      expect(doc.games[0]!.sections).toHaveLength(2)
      expect(doc.games[0]!.sections[0]!.lines).toEqual(['; a comment about the game'])
      expect(doc.games[0]!.sections[0]!.tagPair).toBeUndefined()
      expect(doc.games[0]!.sections[1]!.tagPair).toEqual({ name: 'Board', value: '1' })
    })

    it('comment content between two tags joins the preceding tag\'s section', () => {
      const doc = PBNDocument.fromPBN('[Result ""]\n{ a multi-line\ncomment block }\n[BCFlags "1f"]\n')
      expect(doc.games[0]!.sections).toHaveLength(2)
      expect(doc.games[0]!.sections[0]!.lines).toEqual(['[Result ""]', '{ a multi-line', 'comment block }'])
      expect(doc.games[0]!.sections[1]!.lines).toEqual(['[BCFlags "1f"]'])
    })

    it('a Note tag line is absorbed into the current section rather than starting a new one', () => {
      const doc = PBNDocument.fromPBN('[Auction "N"]\n1S =1= Pass Pass Pass\n[Note "1:natural"]\n[Board "1"]\n')
      expect(doc.games[0]!.sections).toHaveLength(2)
      expect(doc.games[0]!.sections[0]!.lines).toEqual([
        '[Auction "N"]', '1S =1= Pass Pass Pass', '[Note "1:natural"]',
      ])
      expect(doc.games[0]!.sections[1]!.lines).toEqual(['[Board "1"]'])
    })

    it('a malformed bracketed line (no quoted value) joins the current section as body content', () => {
      const doc = PBNDocument.fromPBN('[Board "1"]\n[NotAValidTag]\n')
      expect(doc.games[0]!.sections).toHaveLength(1)
      expect(doc.games[0]!.sections[0]!.lines).toEqual(['[Board "1"]', '[NotAValidTag]'])
    })

    it('a game with only comment content and no real tag is still preserved, not discarded', () => {
      const doc = PBNDocument.fromPBN('; just a stray comment, no tags\n')
      expect(doc.games).toHaveLength(1)
      expect(doc.games[0]!.sections).toHaveLength(1)
      expect(doc.games[0]!.sections[0]!.lines).toEqual(['; just a stray comment, no tags'])
    })

    it('preserves exact original whitespace and content on every line, no trimming', () => {
      const doc = PBNDocument.fromPBN('[Board "1"]\n   indented body text   \n')
      expect(doc.games[0]!.sections[0]!.lines).toEqual(['[Board "1"]', '   indented body text   '])
    })

    it('parses real-world PBN files without throwing, with the expected number of games', () => {
      const cases: [string, number][] = [
        ['Open4thSeat.pbn', 7],
        ['Responder Rebid.pbn', 2],
        ['TOB L5 Hands.pbn', 4],
        ['hand-record-1.pbn', 36],
        ['hand-record-2.pbn', 36],
      ]
      for (const [file, expectedGames] of cases) {
        const doc = PBNDocument.fromPBN(readTestData(file))
        expect(doc.games, file).toHaveLength(expectedGames)
      }
    })

    it('parses tag values correctly from a real hand record file', () => {
      const doc = PBNDocument.fromPBN(readTestData('hand-record-1.pbn'))
      // Document-level header lines, still bearing their "%".
      expect(doc.escapedText[0]).toBe('% PBN 2.1')
      expect(doc.escapedText.every(line => line.startsWith('%'))).toBe(true)

      const first = doc.games[0]!
      expect(first.getTagValue('Board')).toBe('1')
      expect(first.getTagValue('Dealer')).toBe('N')
      expect(first.getTagValue('Vulnerable')).toBe('None')
      expect(first.getDealer()).toBe('N')
      expect(first.getVulnerable()).toBe('None')
      expect(first.getBoard()).toBe(1)
    })

    it('parses a lesson file with multi-line { } comments and custom tags', () => {
      const doc = PBNDocument.fromPBN(readTestData('TOB L5 Hands.pbn'))
      expect(doc.games).toHaveLength(4)
      const first = doc.games[0]!
      expect(first.getTagValue('Event')).toBe('Lesson 5')
      expect(first.getTagValue('BCFlags')).toBe('1f')
      // The comment block's lines live in whichever section (Result's) they followed.
      const resultSection = first.sections.find(s => s.tagPair?.name === 'Result')
      expect(resultSection?.lines.some(l => l.includes('\\CQ lead'))).toBe(true)
    })

    it('parses a file with a leading blank line, missing tags, and a blank line inside a { } comment', () => {
      const doc = PBNDocument.fromPBN(readTestData('Responder Rebid.pbn'))
      // The blank line inside each game's {...} comment block must not split it into extra games.
      expect(doc.games).toHaveLength(2)
      expect(doc.games[0]!.getTagValue('Dealer')).toBe('S')
      expect(doc.games[1]!.getTagValue('Dealer')).toBe('S')
      expect(doc.games[1]!.getTagValue('Event')).toBe('Responder uses new-minor forcing to show 5 spades')
    })

    describe('"{...}" multi-line comment blocks', () => {
      it('a blank line inside an open block does not end the game', () => {
        const doc = PBNDocument.fromPBN('[Board "1"]\n{\nfirst paragraph\n\nsecond paragraph\n}\n[Board "2"]\n')
        expect(doc.games).toHaveLength(1)
        expect(doc.games[0]!.sections).toHaveLength(2)
      })

      it('keeps the blank line as part of the comment section\'s lines', () => {
        const doc = PBNDocument.fromPBN('[Board "1"]\n{\na\n\nb\n}\n')
        expect(doc.games[0]!.sections[0]!.lines).toEqual(['[Board "1"]', '{', 'a', '', 'b', '}'])
      })

      it('a single-line "{ ... }" comment never enters the multi-line state', () => {
        const doc = PBNDocument.fromPBN('[Board "1"]\n{ a single line comment }\n\n[Board "2"]\n')
        // The blank line right after the single-line comment DOES end the game, since the block
        // was already closed on the same line it opened.
        expect(doc.games).toHaveLength(2)
      })

      it('a tag-shaped or "%" line inside an open block is treated as plain comment content', () => {
        const doc = PBNDocument.fromPBN('[Board "1"]\n{\n[Fake "Tag"]\n%not escaped\n}\n[Board "2"]\n')
        expect(doc.games).toHaveLength(1)
        expect(doc.games[0]!.sections).toHaveLength(2)
        expect(doc.games[0]!.sections[0]!.lines).toEqual([
          '[Board "1"]', '{', '[Fake "Tag"]', '%not escaped', '}',
        ])
        expect(doc.escapedText).toEqual([])
      })

      it('an unclosed block at end of file absorbs the rest of the text without throwing', () => {
        const doc = PBNDocument.fromPBN('[Board "1"]\n{\nunterminated comment\n\nstill going')
        expect(doc.games).toHaveLength(1)
        expect(doc.games[0]!.sections[0]!.lines).toEqual([
          '[Board "1"]', '{', 'unterminated comment', '', 'still going',
        ])
      })
    })
  
    it('Parses a game fragment with auction containing notes', () => {
      const doc = PBNDocument.fromPBN(readTestData('Responder Rebid.pbn'))
      expect(doc.games).toHaveLength(2)
      const auction = doc.games[1]!.getAuction()
      expect(auction).toBeDefined()
      expect(auction?.calls).toHaveLength(7)
    })
  
  })

  describe('convertToExportFormat', () => {
    it('adds "% PBN 2.1" and "% EXPORT" as the first escaped lines when they are missing', () => {
      const doc = PBNDocument.fromPBN('%Creator: Example\n[Board "1"]\n')
      doc.convertToExportFormat()
      expect(doc.escapedText).toEqual(['% PBN 2.1', '% EXPORT', '%Creator: Example'])
    })

    it('adds the header even to a document with no escaped text or no games', () => {
      const doc = new PBNDocument()
      doc.convertToExportFormat()
      expect(doc.escapedText).toEqual(['% PBN 2.1', '% EXPORT'])
    })

    it('does not duplicate header lines that are already there, and moves them first', () => {
      const doc = new PBNDocument([], ['%Creator: Example', '% EXPORT', '% PBN 2.1', '%Other'])
      doc.convertToExportFormat()
      expect(doc.escapedText).toEqual(['% PBN 2.1', '% EXPORT', '%Creator: Example', '%Other'])
    })

    it('replaces a different version line with 2.1', () => {
      const doc = new PBNDocument([], ['% PBN 2.0', '%Other'])
      doc.convertToExportFormat()
      expect(doc.escapedText).toEqual(['% PBN 2.1', '% EXPORT', '%Other'])
    })

    it('does not mistake other escaped lines for the header', () => {
      const doc = new PBNDocument([], ['%PBNsomething', '% EXPORTED by tool'])
      doc.convertToExportFormat()
      expect(doc.escapedText).toEqual(['% PBN 2.1', '% EXPORT', '%PBNsomething', '% EXPORTED by tool'])
    })

    it('converts every game', () => {
      const doc = PBNDocument.fromPBN('[Result "9"]\n[Board "1"]\n\n[Result "10"]\n[Board "2"]\n')
      doc.convertToExportFormat()
      expect(doc.games).toHaveLength(2)
      for (const game of doc.games) {
        expect(game.sections).toHaveLength(15)
        expect(game.sections[3]!.tagPair!.name).toBe('Board')
        expect(game.sections[14]!.tagPair!.name).toBe('Result')
      }
    })

    it('is idempotent', () => {
      const doc = PBNDocument.fromPBN('%X\n[Result "9"]\n[Zed "z"]\n[Board "1"]\n\n[Board "2"]\n')
      doc.convertToExportFormat()
      const snapshot = (): string[][] => [doc.escapedText, ...doc.games.map(g => g.sections.flatMap(s => [...s.lines]))]
      const once = JSON.stringify(snapshot())
      doc.convertToExportFormat()
      expect(JSON.stringify(snapshot())).toBe(once)
    })

    // These files were written by BridgeComposer, which already emits export format — so
    // converting them must change nothing. A strong check of the ordering rules against real data.
    it.each(['hand-record-1.pbn', 'hand-record-2.pbn', 'TOB L5 Hands.pbn'])(
      'leaves %s, already in export format, unchanged',
      name => {
        const doc = PBNDocument.fromPBN(readTestData(name))
        const before = JSON.stringify([doc.escapedText, ...doc.games.map(g => g.sections.map(s => s.lines))])
        doc.convertToExportFormat()
        const after = JSON.stringify([doc.escapedText, ...doc.games.map(g => g.sections.map(s => s.lines))])
        expect(after).toBe(before)
      }
    )

    it('brings a file that is not in export format into it, keeping every game', () => {
      const doc = PBNDocument.fromPBN(readTestData('Open4thSeat.pbn'))
      const gameCount = doc.games.length
      doc.convertToExportFormat()
      expect(doc.games).toHaveLength(gameCount)
      for (const game of doc.games) {
        expect(game.sections.slice(0, 15).map(s => s.tagPair!.name)).toEqual([
          'Event', 'Site', 'Date', 'Board', 'West', 'North', 'East', 'South',
          'Dealer', 'Vulnerable', 'Deal', 'Scoring', 'Declarer', 'Contract', 'Result',
        ])
        expect(game.getAuction()).toBeDefined()
      }
    })
  })
})
